# Generated by Django 5.2.5 on 2025-08-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('Gram', 'Gram'), ('Kg', 'Kg'), ('Liter', 'Liter'), ('Piece', 'Piece')], default='Piece', max_length=10)),
                ('barcode_number', models.CharField(default='000000', max_length=50, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
