# Generated by Django 5.2.5 on 2025-08-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcode/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode_number',
            field=models.CharField(default='000000', max_length=50, null=True, unique=True),
        ),
    ]
